/**
 * Studio drafter (V1) — template-based draft generator.
 *
 * Sprint 1: no LLM. Takes a source (inbox body, classified tags, or a
 * release notes string) and produces 3 drafts in different formats
 * (X thread, LinkedIn post, blog intro) using parameterised templates.
 *
 * Sprint 2+: optional LLM call (when LLMX_STUDIO_LLM=1) to replace
 * the template body with a real model-generated draft.
 */
export type DraftFormat = 'x-thread' | 'linkedin' | 'blog';

export interface DraftInput {
  text: string;
  tags: string[];
  source: 'inbox' | 'decision' | 'release' | 'synthesis';
  context?: string; // optional extra context (release name, decision id, etc.)
}

export interface Draft {
  format: DraftFormat;
  filename: string;
  body: string;
  generated_at: string;
}

export function buildDrafts(input: DraftInput): Draft[] {
  const ts = new Date().toISOString();
  const title = extractTitle(input.text);
  const summary = summarize(input.text);
  const tagLine = input.tags.length > 0
    ? input.tags.map((t) => `#${t}`).join(' ')
    : '';
  const ctx = input.context ? ` (${input.context})` : '';

  return [
    {
      format: 'x-thread',
      filename: 'x-thread',
      body: renderXThread({ title, summary, tagLine, ctx }),
      generated_at: ts,
    },
    {
      format: 'linkedin',
      filename: 'linkedin',
      body: renderLinkedIn({ title, summary, tagLine, ctx }),
      generated_at: ts,
    },
    {
      format: 'blog',
      filename: 'blog',
      body: renderBlog({ title, summary, tagLine, ctx }),
      generated_at: ts,
    },
  ];
}

function renderXThread(p: { title: string; summary: string; tagLine: string; ctx: string }): string {
  return [
    `# X thread${p.ctx}`,
    ``,
    `1/ ${p.title}`,
    ``,
    `2/ ${p.summary}`,
    ``,
    `3/ Why it matters: this is one of those small details that compounds. Worth a second look if you're building anything similar.`,
    ``,
    `4/ If you ship something like this, you'll save yourself the next time you switch tools / context / agent.`,
    ``,
    `5/ ${p.tagLine || '#buildinpublic'}`,
    ``,
    `> _Edit me before posting. Generated by \`llmx studio draft\`._`,
  ].join('\n');
}

function renderLinkedIn(p: { title: string; summary: string; tagLine: string; ctx: string }): string {
  return [
    `# LinkedIn post${p.ctx}`,
    ``,
    `${p.title}.`,
    ``,
    `${p.summary}`,
    ``,
    `Three things I took away from this:`,
    ``,
    `- The first is the obvious win.`,
    `- The second is the long-term compounding effect.`,
    `- The third is what changes for the next person who tries it.`,
    ``,
    `Curious to hear from others who've shipped similar. What's worked, what hasn't?`,
    ``,
    `${p.tagLine}`,
    ``,
    `> _Edit me before posting. Generated by \`llmx studio draft\`._`,
  ].join('\n');
}

function renderBlog(p: { title: string; summary: string; tagLine: string; ctx: string }): string {
  return [
    `# ${p.title}`,
    ``,
    `> ${p.summary}`,
    ``,
    `## Context`,
    ``,
    `${p.ctx || 'This post is a working note, not a polished essay.'}`,
    ``,
    `## What I tried`,
    ``,
    `_Replace this section with what you actually did._`,
    ``,
    `## What I learned`,
    ``,
    `- Insight 1`,
    `- Insight 2`,
    `- Insight 3`,
    ``,
    `## What's next`,
    ``,
    `_Replace this section with what you'd do differently or build next._`,
    ``,
    `---`,
    ``,
    `${p.tagLine}`,
    ``,
    `> _Edit me before publishing. Generated by \`llmx studio draft\`._`,
  ].join('\n');
}

function extractTitle(text: string): string {
  const first = text.trim().split('\n').find((l) => l.trim().length > 0) ?? '';
  const cleaned = first.replace(/^#+\s*/, '').trim();
  if (cleaned.length === 0) return 'Untitled idea';
  if (cleaned.length > 90) return cleaned.slice(0, 87) + '...';
  return cleaned;
}

function summarize(text: string): string {
  const lines = text
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0 && !l.startsWith('#') && !l.startsWith('- '));
  const body = lines.slice(0, 3).join(' ').replace(/\s+/g, ' ');
  if (body.length === 0) return 'No body content yet — add a sentence or two here.';
  if (body.length > 280) return body.slice(0, 277) + '...';
  return body;
}
