/**
 * Codex adapter — renders `AGENTS.md` from the current LLMX context.
 *
 * Codex (OpenAI's coding agent) reads `AGENTS.md` to learn about the project.
 * The export follows the same philosophy as the Claude Code adapter: the
 * canonical state lives in `project.llmx/`, and `AGENTS.md` is regenerated
 * from it on demand.
 */
import type { Repository } from '../../core/index.js';

export async function exportForCodex(repo: Repository): Promise<string> {
  const [state, tasks, decisions, history, skills] = await Promise.all([
    repo.readProjectState(),
    repo.readTasks(),
    repo.readDecisions(),
    repo.readSessionHistory(),
    repo.readSkillIndex(),
  ]);

  const openTasks = tasks.tasks.filter((t) => t.status === 'pending' || t.status === 'in_progress');
  const lastSession = history[history.length - 1];

  const lines: string[] = [];
  lines.push('# Shared Agent Context (Codex)');
  lines.push('');
  lines.push('This file is auto-generated by `llmx export codex` from the LLMX');
  lines.push('context in `project.llmx/`. To change it, edit the source files');
  lines.push('and re-run `llmx export codex`.');
  lines.push('');
  lines.push('## Workflow');
  lines.push('');
  lines.push('Before starting work:');
  lines.push('1. Read `project.llmx/memory/project-state.md`.');
  lines.push('2. Read `project.llmx/memory/tasks.json` and pick the next open task.');
  lines.push('3. Read the most recent entries of `project.llmx/memory/decisions.jsonl`.');
  lines.push('4. Read `project.llmx/sessions/latest.md` for context from the last session.');
  lines.push('5. Read `project.llmx/skills/index.json` and load any skill that matches your task.');
  lines.push('');
  lines.push('During work:');
  lines.push('- Do not duplicate existing architecture — check `project-state.md` first.');
  lines.push('- Prefer adding a decision entry to `decisions.jsonl` over free-form prose.');
  lines.push('- Use skills from `project.llmx/skills/` when they apply.');
  lines.push('');
  lines.push('After work:');
  lines.push('1. Update `project.llmx/sessions/latest.md` (via `llmx session save`).');
  lines.push('2. Add decisions to `project.llmx/memory/decisions.jsonl`.');
  lines.push('3. Update task statuses in `project.llmx/memory/tasks.json`.');
  lines.push('4. Mention changed files in the session summary.');
  lines.push('');
  lines.push('## Project state');
  lines.push('');
  lines.push(state.trim());
  lines.push('');
  lines.push('## Open tasks');
  lines.push('');
  if (openTasks.length === 0) {
    lines.push('_No open tasks right now._');
  } else {
    for (const t of openTasks) {
      const tags = t.tags.length > 0 ? `  [${t.tags.join(', ')}]` : '';
      lines.push(`- [${t.status}] **${t.title}**${tags}`);
      if (t.description) {
        for (const ln of t.description.split('\n')) {
          lines.push(`  ${ln}`);
        }
      }
    }
  }
  lines.push('');
  lines.push('## Recent decisions');
  lines.push('');
  if (decisions.length === 0) {
    lines.push('_No decisions yet._');
  } else {
    for (const d of decisions.slice(-5).reverse()) {
      const by = d.decidedBy ? ` _(${d.decidedBy})_` : '';
      lines.push(`- **${d.title}**${by} — _${d.createdAt}_`);
      if (d.rationale) lines.push(`  - ${d.rationale}`);
    }
  }
  lines.push('');
  lines.push('## Latest session');
  lines.push('');
  if (lastSession) {
    lines.push(`> ${lastSession.agent} — ${lastSession.createdAt}`);
    lines.push('');
    lines.push(lastSession.summary);
    if (lastSession.changedFiles.length > 0) {
      lines.push('');
      lines.push('Files changed:');
      for (const f of lastSession.changedFiles) lines.push(`- \`${f}\``);
    }
  } else {
    lines.push('_No session recorded yet._');
  }
  lines.push('');
  lines.push('## Skills available');
  lines.push('');
  if (skills.skills.length === 0) {
    lines.push('_No skills installed._');
  } else {
    for (const s of skills.skills) {
      lines.push(`### \`${s.name}\``);
      if (s.description) lines.push(s.description);
      lines.push(`Read it: \`project.llmx/skills/${s.path}\``);
      lines.push('');
    }
  }
  lines.push('## Security');
  lines.push('');
  lines.push('- Never read or echo `.env` files or other secret material into shared context.');
  lines.push('- The LLMX MCP server runs in `localOnly` mode by default — do not enable network egress.');
  lines.push('- If you need a new permission, ask the human.');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('_Re-run `llmx export codex` after each session to keep this in sync._');

  const body = lines.join('\n');
  await repo.writeText(repo.paths.agentsFile, body);
  return body;
}
